Repository dil-classroom/projet-marzullo_matias_monti_golay_perrenoud, pull requests merged in 2022-04, with the labels that each got.

#46 Add option to show app version
  pom.xml
  src/main/java/org/hyde/Hyde.java
Labels: enhancement

#42 [TOREVIEW] Ajout de la commande de suppression de dossier
  src/main/java/org/hyde/Clean.java
Labels: user story

#49 [TO REVIEW] Implement new command
  src/main/java/org/hyde/New.java
Labels: enhancement

#57 Add build folder to gitignore
  .gitignore
Labels: bug

#63 Ajout du dossier template et du fichier layout.html
  src/main/java/org/hyde/New.java
Labels: enhancement
