Repository dil-classroom/projet-marzullo_matias_monti_golay_perrenoud, pull requests merged in 2022-03, with the labels that each got.

#16 fix: Remove target folder
  target/classes/App.class
Labels: bug

#13 docs: add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#40 [To Review] Change project name
  pom.xml
  src/main/java/org/hyde/Build.java
  src/main/java/org/hyde/Clean.java
  src/main/java/org/hyde/Main.java
  src/main/java/org/hyde/New.java
  src/main/java/org/hyde/Serve.java
Labels: enhancement

#41 Commandline interface
  pom.xml
  src/main/java/org/hyde/Build.java
  src/main/java/org/hyde/Clean.java
  src/main/java/org/hyde/Hyde.java
  src/main/java/org/hyde/Main.java
  src/main/java/org/hyde/New.java
  src/main/java/org/hyde/Serve.java
Labels: enhancement
