Repository dil-classroom/projet-marzullo_matias_monti_golay_perrenoud, pull requests merged in 2022-06, with the labels that each got.

#80 47 make the path in the commands optional
  src/main/java/org/hyde/Build.java
  src/main/java/org/hyde/Clean.java
  src/main/java/org/hyde/New.java
  src/main/java/org/hyde/Serve.java
Labels: enhancement

#83 81 build functionnality fixes
  src/main/java/org/hyde/Build.java
Labels: bug

#87 Major rewrite of "Build" function
  src/main/java/org/hyde/Build.java
Labels: bug, enhancement

#85 Major refactor + additionnal bug fixes
  pom.xml
  src/main/java/org/hyde/Clean.java
  src/main/java/org/hyde/Hyde.java
  src/main/java/org/hyde/New.java
  src/main/java/org/hyde/Serve.java
Labels: bug, documentation, enhancement

#97 Add user manual
  README.md
Labels: documentation

#100 Remove unused imports from files
  src/main/java/org/hyde/Utils/SiteBuilder.java
Labels: refactor

#101 Rename documents to cleaner names
  docs/class-diagram.drawio
  docs/markers.md
  docs/sequence-diagram-build.drawio
  docs/sequence-diagram-watch.drawio
Labels: refactor
