Repository dil-classroom/projet-marzullo_matias_monti_golay_perrenoud, pull requests merged in 2022-05, with the labels that each got.

#61 Ajout de la fonction d'ouverture d'un fichier HTML
  pom.xml
  src/main/java/org/hyde/Serve.java
Labels: enhancement

#75 55 implement file inlcudes
  src/main/java/org/hyde/Build.java
  src/main/java/org/hyde/New.java
Labels: enhancement

#77 Add javadoc generation and release
  .github/workflows/milestone-release.yml
  pom.xml
  src/main/resources/assemble.xml
  src/main/resources/stylesheet.css
Labels: documentation, enhancement

#79 Fix potential input resource leak
  src/main/java/org/hyde/Build.java
Labels: bug
